[build]
builder = "DOCKERFILE"
dockerfilePath = "fe/Dockerfile"
buildCommand = "docker build -t anybot-fe ."

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 30
startupTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

# Railway environment variables
[variables]
PORT = "8080"
     = "true"
PROXY_PASS = "http://anybotbe.railway.internal" 