[build]
builder = "DOCKERFILE"
dockerfilePath = "fe/Dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 60
startupTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Railway environment variables
[variables]
ENABLE_ALPINE_PRIVATE_NETWORKING = "true"
PROXY_PASS = "http://anybot-be.railway.internal:8000" 